Manage offer: presale, sale and closed stages
IX-Swap/interface pull request #1586
Opened 2023-02-10 15:27 UTC by witchaotic

2023-02-10 19:02 UTC, vflorea requested changes

2023-02-10 19:02 UTC, vflorea commented on src/state/launchpad/hooks.ts
> +        .get(`/offers/${id}/investments?${query.join('&')}`)
no need to format query params.
apiService.get can have 3 parameters.
`  get: async function get<T = any>(uri: string, config?: RequestConfig, params?: Record<string, string | number>) { },`
so you can send query params as an object:
`apiService
        .get(`/offers/${id}/investments`, undefined, {offset: size, page, stage})` and it knows what to do <3, and no need for that extra operations

2023-02-10 19:09 UTC, vflorea commented
Also, please please adjust the back link from extract page. 
I am on manage page. I click on extract data. I click on the back button. The link is not correct. It needs to use a different id

2023-02-11 17:03 UTC, witchaotic commented on src/components/LaunchpadIssuance/ManageOffer/investments/InvestmentsList.tsx
> +                <Raw>{item.amount.toLocaleString()}</Raw>
everywhere where in design it's USD, it's either tokenSymbol or investingTokenSymbol. we don't use USD, that is just the mock data the designer uses. 
i will add our symbol here

2023-02-11 18:27 UTC, witchaotic commented on src/state/launchpad/hooks.ts
> +        .get(`/offers/${id}/investments?${query.join('&')}`)
this won't work, because of order. axios adds brackets to it, and it can be turned off in the next version only. now there is an option for a serializer, to at least be able to reuse this formatting technique.

2023-02-11 18:55 UTC, witchaotic commented
@vflorea fixed all your comments, please check.

also regarding your last comment - I will have to push at the same time this PR on backend - [this one](https://github.com/IX-Swap/backend/pull/954/files). otherwise getting the offer by issuanceId won't work.

also added redirect from issuance page. and redid some paths for consistency.

2023-02-13 08:34 UTC, vflorea approved these changes

2023-02-13 08:36 UTC, merged