Ixs 2765 update vetting form
IX-Swap/interface pull request #1644
Opened 2023-03-20 03:37 UTC by harryng22

2023-03-20 06:20 UTC, witchaotic requested changes

2023-03-20 06:20 UTC, witchaotic commented on src/components/LaunchpadIssuance/IssuanceForm/Vetting/constants.ts
> +export const offeringData = [
could you please rename it to strategyOptions? offeringData sound like an object containing data about the offer.

2023-03-20 11:01 UTC, harryng22 commented on src/assets/launchpad/svg/info-icon.svg
I have resolved it

2023-03-21 06:09 UTC, witchaotic requested changes

2023-03-21 06:09 UTC, witchaotic commented on src/components/LaunchpadIssuance/IssuanceForm/Vetting/index.tsx
> +                checked={offer.option === (values.smartContractStrategy ? values.smartContractStrategy : defaultValues.smartContractStrategy)}
we have `useVettingFormInitialValues` that can be used for setting default values, so you can use here just `values.smartContractStrategy`

2023-03-21 06:09 UTC, witchaotic commented on src/components/LaunchpadIssuance/IssuanceForm/Vetting/index.tsx
> +              {strategyOptions.map((offer, idx) => <StrategyCard key={offer.option + idx}
how about you rename `offer` here to strategy/option/item?

2023-03-21 06:55 UTC, harryng22 commented on src/components/LaunchpadIssuance/IssuanceForm/Vetting/index.tsx
> +                checked={offer.option === (values.smartContractStrategy ? values.smartContractStrategy : defaultValues.smartContractStrategy)}
This is radio button, so we need this expression for the checked property

2023-03-21 08:11 UTC, merged