Ixs 2864 enable the submit button when no error
IX-Swap/interface pull request #1709
Opened 2023-04-07 03:13 UTC by harryng22

2023-04-07 04:50 UTC, witchaotic approved these changes

2023-04-07 05:01 UTC, witchaotic requested changes

2023-04-07 05:01 UTC, witchaotic commented on src/components/LaunchpadIssuance/utils/form.ts
>    const hasErrors = Object.keys(errors).length > 0
Please recheck the task, I left some comments there. you need to leave the `notTouched` check. 
you should disable it only if there are visible errors, basically the `isDraftDisabled` check. if there are no visible errors, the user should be able to click, so the whole form validation would be triggered(all touched). 
this is really easy to reproduce with new forms - some fields are empty, the user cannot click on the submit button, yet it doesn't know what it requires for submitting. 
we still show only the touched errors, so they can work on the form and save draft as many times as they want. but when clicking submit they should either see all errors or submit the form(if no errors).
I hope I explained it well, please check the task comment as well.

2023-04-07 07:21 UTC, harryng22 commented on src/components/LaunchpadIssuance/utils/form.ts
>    const hasErrors = Object.keys(errors).length > 0
I think it's not intuitive for users to know they need to touch (change something) to enable the submit button after they save the form, and come back later. So I delete the touched property.
I changed code back to before.

2023-04-07 09:15 UTC, witchaotic commented on src/components/LaunchpadIssuance/utils/form.ts
>    const hasErrors = Object.keys(errors).length > 0
yes, it's not intuitive, that's why we should **enable** the submit button if there are no **visible** errors, so the user can click on it and see all the errors.   
you can also add a message with `showError` for the user to check his form again in that case.

2023-04-10 06:42 UTC, witchaotic commented on src/components/LaunchpadIssuance/utils/form.ts
>    const hasErrors = Object.keys(errors).length > 0
@harryng22 this one

2023-04-10 09:30 UTC, witchaotic requested changes

2023-04-10 09:30 UTC, witchaotic commented on src/components/LaunchpadIssuance/utils/form.ts
> -export const isDraftDisabled = (errors: any, touched: any) => {
for `isSubmitDisabled` you don't need the required exception, all errors count. basically the getIsDisabled should not be called or always return true

2023-04-10 10:27 UTC, witchaotic approved these changes

2023-04-10 10:27 UTC, merged