2899 Add info icon to pre-sale invest
IX-Swap/interface pull request #1721
Opened 2023-04-11 04:05 UTC by harryng22

2023-04-11 04:39 UTC, witchaotic requested changes

2023-04-11 04:39 UTC, witchaotic commented on src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx
> +                <Info size="13" color={theme.launchpad.colors.text.caption} />
there should be some information on hover, if not the info icon here is misleading. please contact Olga for the text

2023-04-12 02:52 UTC, harryng22 commented on src/components/LaunchpadOffer/InvestDialog/content/Sale.tsx
> +                <Info size="13" color={theme.launchpad.colors.text.caption} />
I updated

2023-04-12 07:34 UTC, witchaotic approved these changes

2023-04-12 07:36 UTC, merged