2936 The Amount field should be disabled when the investor clicks No
IX-Swap/interface pull request #1761
Opened 2023-04-20 03:15 UTC by harryng22

2023-04-20 04:54 UTC, witchaotic requested changes

2023-04-20 04:54 UTC, witchaotic commented on src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx
you need to disable the field, not the submit button. you can still submit with "no"

2023-04-20 04:54 UTC, witchaotic commented on src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx
> +  const [amount, setAmount] = React.useState("")
there is no need for this state, you have values bellow.

2023-04-20 04:54 UTC, witchaotic commented on src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx
>    }, [])
you need to fix the dependencies here

2023-04-20 07:08 UTC, harryng22 commented on src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx
> +  const [amount, setAmount] = React.useState("")
I used it, but it's not working when I want to set values.amount to 0 in onChangeInterested

2023-04-20 07:08 UTC, harryng22 commented on src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx
>    }, [])
I tried, but it doesn't work

2023-04-20 12:27 UTC, witchaotic requested changes

2023-04-20 12:27 UTC, witchaotic commented on src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx
>    }, [])
why use an empty useCallback. remove the callback then.

2023-04-21 02:05 UTC, harryng22 commented on src/components/LaunchpadOffer/InvestDialog/content/RegisterToInvest.tsx
>    }, [])
Ok I have removed it

2023-04-21 04:39 UTC, witchaotic approved these changes

2023-04-21 04:39 UTC, merged