KYC V2 UI upgraded and manage to open both individuals KYC forms
IX-Swap/interface pull request #2337
Opened 2024-05-27 03:02 UTC by kapildave07

## Description

The KYC V2 UI has been upgraded, allowing users to open and manage KYC forms for both individual customers(old and new) more efficiently. This enhancement improves the user experience and streamlines the identity verification process.

## Changes

- UI Upgraded: Refers to improvements in the design, functionality, and usability of the interface that users interact with. 
used the same components and code that we are using in other components 
- Open Both Individuals KYC Forms: The upgraded UI now supports accessing and managing KYC forms for different types of individual customers, enhancing efficiency and user experience.

## Attached Links

1. Jira ticket: https://investax.atlassian.net/browse/IXSPD1-1228
https://investax.atlassian.net/browse/IXSPD1-1234
2. Documents:

## Checklist

- [x] Manual tests
- [x] The pull request doesn't affect existing feature

## For reviewers

- Ensure new code doesn't break existing features
- Reviewer shouldn't merge if there are pending unresolved comments

2024-05-27 03:30 UTC, thi-investax commented on src/pages/AppRoutes.tsx
> +const IndividualKYCNew = lazy(() => import('pages/KYC/NewIndividualKycForm'))
Suggest rename `IndividualKYCV2`

2024-05-27 03:30 UTC, thi-investax commented on src/pages/AppRoutes.tsx
> +    component: IndividualKYCNew,
I suggest rename `IndividualKycNew` to `IndividualKycV2`

2024-05-27 10:58 UTC, thuongthanhto1 approved these changes

2024-05-28 06:16 UTC, thi-investax requested changes

2024-05-28 06:16 UTC, thi-investax commented on src/components/AdminKyc/index.tsx
> +  console.log(kyc, 'jjjjkjk')
Should remove this log

2024-05-28 06:16 UTC, thi-investax commented on src/components/KycReviewModal/index.tsx
> +  }
dont please do conditional rendering outside 

version == 'v2' ? <KycReviewModalV2 isOpen={isOpen} onClose={onClose} data={data} />  : <KycReviewModal>

2024-05-28 06:16 UTC, thi-investax commented on src/components/KycReviewModal/KycReviewModalV2.tsx
> +  //   const needResubmit = [KYCStatuses.DRAFT, KYCStatuses.FAILED].includes(data?.status as any)
remove all commented code

2024-05-28 06:21 UTC, kapildave07 commented on src/components/KycReviewModal/KycReviewModalV2.tsx
> +  //   const needResubmit = [KYCStatuses.DRAFT, KYCStatuses.FAILED].includes(data?.status as any)
some of functions can be useful while APi integrations. That’s why i commented code. after the API integration is done i will remove unused code.

2024-05-29 12:27 UTC, thi-investax requested changes

2024-05-29 12:27 UTC, thi-investax commented on src/pages/KYC/NewIndividualKycForm.tsx
> +  }
@kapildave07  I think you are making the same mistake again you made in the LBP. 
this is not the right way to check if a form can be submitted. hi  @thuongthanhto1 ,do you have any recommendation?

2024-05-30 03:05 UTC, thi-investax commented on src/pages/KYC/NewIndividualKycForm.tsx
> +    setCanSubmit(true)
Is it possible that we use errors from Formik.

![image](https://github.com/IX-Swap/interface/assets/118243127/84c963c0-d23e-4951-bce0-773f8fba45cc)

2024-06-03 03:20 UTC, thi-investax commented on src/pages/KYC/EmailVerificationSection.tsx
> +    if (onSuccess) onSuccess(emailType === 'primary-email' ? 'personal' : 'businessEmail')
@kapildave07  could we make these values Enum? later on we just need to update for one place

2024-06-04 00:39 UTC, thi-investax commented
![image](https://github.com/IX-Swap/interface/assets/118243127/231cbbc0-d949-41d7-af65-0758288f245e)
@kapildave07 , when typing the input show error already. should only show when we don't focus the form

2024-06-04 00:41 UTC, thi-investax commented
![image](https://github.com/IX-Swap/interface/assets/118243127/6b982432-c056-4d9a-8683-9488fa8d704d)
enter a new email but `Email already exist` still appears

2024-06-04 03:02 UTC, thi-investax commented on src/pages/KYC/IndividualKycFormV2.tsx
> +                : undefined
this condtion looks unreadable


Please consider refactor into this 

```js
const getValidationSchema = (selectedCheckbox) => {
  if (selectedCheckbox === SecondaryContactTypeV2.BUSINESS_EMAIL) {
    return businessEmailSchema;
  }
  if (selectedCheckbox === SecondaryContactTypeV2.TELEGRAM) {
    return undefined;
  }
  return individualErrorsSchemaV2;
}
```

2024-06-04 03:28 UTC, thi-investax commented on src/pages/KYC/IndividualKycFormV2.tsx
> +                        {!kyc?.individual?.email && !isPersonalVerified && (
chnage this to !kyc?.individual?.isEmailVerified

2024-06-04 03:28 UTC, thi-investax commented on src/pages/KYC/IndividualKycFormV2.tsx
> +                        {isPersonalVerified || kyc?.individual?.email ? <VerificationConfirmation /> : null}
!kyc?.individual?.isEmailVerified
 
 should change isPersonalVerified  -> isPersonalEmailVerified

2024-06-04 03:45 UTC, thi-investax commented
should change the component name from `EmailVerificationSection` -> `SecondaryContactOption` .

2024-06-10 03:28 UTC, merged